apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: distributed-permanent
allowVolumeExpansion: true
parameters:
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
