apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-permanent
allowVolumeExpansion: true
parameters:
  dataLocality: 'strict-local'
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
