---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: picluster-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.0.200-192.168.0.250

---

# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-svc-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.0.251-192.168.0.254
  - 192.168.0.105/32

---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb
spec:
  ipAddressPools:
  - picluster-pool
  - local-svc-pool


