apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: cluster
  namespace: postgres
spec:
  instances: 3
  postgres:
    version: 'latest'
    extensions:
      - name: 'timescaledb'
      - name: 'timescaledb_toolkit'
  pods:
    persistentVolume:
      size: '30Gi'
      storageClass: 'local-permanent'
  sgInstanceProfile: 'size-s'
